name: Install Python3 Package gen_data_model
on:
  push:
    branches: [ master ]
    paths:
      - 'gen_data_model/**'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'setup.py'
  pull_request:
    branches: [ master ]
    paths:
      - 'gen_data_model/**'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'setup.py'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
        pip install -r requirements.txt
    - name: Build and publish
      run: |
        python setup.py --github sdist bdist_wheel
