name: TOC Generator gen_data_model
on: push
  push:
    paths:
      - '**.md'
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v2
