name: gen_data_model toc generator
on: push
  push:
    paths:
      - '**.md'
jobs:
  generateTOC:
    name: gen_data_model toc generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v2
